### ISSUE TITLE
Can this generate files of. obj or. fbx types?

### ISSUE THREAD

**Issue by Volleria** [Stability-AI/stable-fast-3d#17]

**Comment by vork** [comment]
We currently don't have that implemented, as obj with textures is slightly annoying (multiple files). So, it would require zipping everything for the radio demo. However, we use trimesh, and you can easily save everything in a different format if you want (https://github.com/Stability-AI/stable-fast-3d/blob/main/run.py#L118-L124).

FBXs do not have many OS implementations due to the proprietary nature of the format.

**Comment by Volleria** [comment]
I tried generating  .obj file and it worked, thanks!
![image](https://github.com/user-attachments/assets/d87645d9-b4e4-4a15-a73a-371b7b6073ac)

**Comment by bc129697** [comment]
> I tried generating .obj file and it worked, thanks! ![image](https://private-user-images.githubusercontent.com/65217991/355163890-d87645d9-b4e4-4a15-a73a-371b7b6073ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzEwMzIsIm5iZiI6MTcyNjEzMDczMiwicGF0aCI6Ii82NTIxNzk5MS8zNTUxNjM4OTAtZDg3NjQ1ZDktYjRlNC00YTE1LWE3M2EtMzcxYjdiNjA3M2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4NDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZTE4NmY1NjViNjVlNzcwZDFlNzgwYWI2NmFjZDVmZjg1ZGI5MzYyMDc5NDkzY2QxNGVlZGQyMWJiMzRhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmAWKC6gUWdbDnjAS3Z3a99hWOxA0d4Ho3A0X4IpUtY)

Hi，how do you generate the obj file?Thanks
